spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLySieuThi;encrypt=true;trustServerCertificate=true;

# Tai khoan sa vua tao
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
